import type { Article, Category, Tag } from '~/types'

/** 生成模拟文章数据 */
export function useMockData() {
  const categories: Category[] = [
    { id: 1, name: '前端开发', slug: 'frontend', articleCount: 12 },
    { id: 2, name: '后端开发', slug: 'backend', articleCount: 8 },
    { id: 3, name: 'AI 与机器学习', slug: 'ai-ml', articleCount: 6 },
    { id: 4, name: '开源项目', slug: 'open-source', articleCount: 5 },
    { id: 5, name: '技术随笔', slug: 'thoughts', articleCount: 10 },
  ]

  const tags: Tag[] = [
    { id: 1, name: 'Vue 3', slug: 'vue3' },
    { id: 2, name: 'TypeScript', slug: 'typescript' },
    { id: 3, name: 'Nuxt', slug: 'nuxt' },
    { id: 4, name: 'Tailwind CSS', slug: 'tailwindcss' },
    { id: 5, name: 'Node.js', slug: 'nodejs' },
    { id: 6, name: 'Python', slug: 'python' },
    { id: 7, name: 'Docker', slug: 'docker' },
    { id: 8, name: 'LLM', slug: 'llm' },
  ]

  const articles: Article[] = [
    {
      id: 1,
      title: '使用 Nuxt 3 构建现代化博客平台的完整指南',
      summary: '本文将详细介绍如何使用 Nuxt 3 从零搭建一个功能完善的博客系统，涵盖 SSR 渲染、SEO 优化、Tailwind CSS 样式设计等核心内容。',
      content: '',
      coverImage: 'https://picsum.photos/seed/nuxt3/800/400',
      category: categories[0],
      tags: [tags[0], tags[1], tags[2]],
      author: { id: 1, name: '张三', avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Felix', bio: '全栈开发工程师' },
      createdAt: '2025-03-20',
      updatedAt: '2025-03-20',
      readingTime: 12,
      viewCount: 1280,
      likeCount: 86,
    },
    {
      id: 2,
      title: 'TypeScript 5.8 新特性全面解读：类型系统的又一次飞跃',
      summary: 'TypeScript 5.8 带来了多项令人兴奋的新特性，包括改进的类型推断、新的装饰器支持以及性能优化。本文逐一解读这些新特性的实际应用场景。',
      content: '',
      coverImage: 'https://picsum.photos/seed/typescript/800/400',
      category: categories[0],
      tags: [tags[1]],
      author: { id: 2, name: '李四', avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Aneka', bio: '前端架构师' },
      createdAt: '2025-03-18',
      updatedAt: '2025-03-19',
      readingTime: 8,
      viewCount: 960,
      likeCount: 52,
    },
    {
      id: 3,
      title: '大语言模型在代码生成中的应用与挑战',
      summary: '探讨当前大语言模型（LLM）在代码自动生成领域的最新进展，分析 Copilot、Cursor 等工具的技术原理，以及开发者如何高效利用 AI 辅助编程。',
      content: '',
      coverImage: 'https://picsum.photos/seed/llm-code/800/400',
      category: categories[2],
      tags: [tags[7], tags[5]],
      author: { id: 1, name: '张三', avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Felix', bio: '全栈开发工程师' },
      createdAt: '2025-03-15',
      updatedAt: '2025-03-16',
      readingTime: 15,
      viewCount: 2100,
      likeCount: 128,
    },
    {
      id: 4,
      title: 'Docker Compose 实战：微服务本地开发环境一键搭建',
      summary: '通过一个实际的微服务项目，演示如何使用 Docker Compose 编排多个服务，实现本地开发环境的快速搭建与管理，大幅提升团队开发效率。',
      content: '',
      coverImage: 'https://picsum.photos/seed/docker/800/400',
      category: categories[1],
      tags: [tags[6], tags[4]],
      author: { id: 3, name: '王五', avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Bubba', bio: 'DevOps 工程师' },
      createdAt: '2025-03-12',
      updatedAt: '2025-03-12',
      readingTime: 10,
      viewCount: 750,
      likeCount: 43,
    },
    {
      id: 5,
      title: 'Tailwind CSS v4 深度体验：从原子化到设计系统',
      summary: 'Tailwind CSS v4 引入了全新的引擎和配置方式，本文通过实际项目对比 v3 和 v4 的差异，探讨原子化 CSS 在设计系统中的最佳实践。',
      content: '',
      coverImage: 'https://picsum.photos/seed/tailwind/800/400',
      category: categories[0],
      tags: [tags[3]],
      author: { id: 2, name: '李四', avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Aneka', bio: '前端架构师' },
      createdAt: '2025-03-10',
      updatedAt: '2025-03-10',
      readingTime: 7,
      viewCount: 680,
      likeCount: 39,
    },
    {
      id: 6,
      title: '开源之路：我维护一个千星项目的一年总结',
      summary: '回顾过去一年维护开源项目的心路历程，分享社区运营、Issue 管理、版本发布的经验教训，以及开源对个人技术成长的深远影响。',
      content: '',
      coverImage: 'https://picsum.photos/seed/opensource/800/400',
      category: categories[3],
      tags: [tags[0], tags[1]],
      author: { id: 1, name: '张三', avatar: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Felix', bio: '全栈开发工程师' },
      createdAt: '2025-03-08',
      updatedAt: '2025-03-08',
      readingTime: 6,
      viewCount: 1500,
      likeCount: 98,
    },
  ]

  return { articles, categories, tags }
}
